### PR TITLE
mit Observable und co

### PR DESCRIPTION
**Pull request by CarstenKoenig**
hey - kannst Du Dir ja mal anschauen, ich denke vor allem der Teil mit dem Observable und dem vereinfachten Handling (kein dynamic nötig) dürfte vielleicht interessant sein ;)

### CODE REVIEW

**Comment by SCullman** [comment]
Carsten, wie hängt man denn mehrere, auch unterschiedliche  Eventhandler an den PublishNewState Stream ran?

**Comment by jfellien** [comment]
@SCullman du kannst mit `aggregates.PublishNewState.Subscribe(yourNextHandler)` neue Handler hinzufügen.

**Comment by SCullman** [comment]
Klar doch, danke.

2015-07-01 8:36 GMT+02:00 Janek <notifications@github.com>:

**Comment by CarstenKoenig** [comment]
yes it works without RX but you loose most of the nice functions like `OfType` and the easier subscribe as well as the `Subject` I use internally - yeah you could implement those yourself but it's not totally trivial code and DRY and stuff ... but if you want I'll do

**Comment by CarstenKoenig** [comment]
btw: sorry for the german/english mixup ... will change this ;)

**Comment by CarstenKoenig** [comment]
I've removed the dependencies on RX - but the implementations might not be optimal (should work though)

**Comment by CarstenKoenig** [comment]
to make the `And` stuff happen I need to *break*  the `IDisposable` return - might be no big deal - I'll show you an example shortly

**Comment by CarstenKoenig** [comment]
ok - now you can do something like this too:

    aggregates
        .PublishNewState
        .Flatten()
        .SentEventsTo<SampleEventRaised>(sampleEventHandler.HandleMessage)
        .AndTo<IAmAnEventMessage>(_ => { Console.WriteLine("--Message--\n"); });

better?

**Comment by CarstenKoenig** [comment]
removed the rest of the technical stuff from `Aggregates` public interface - now this is how you attach handlers:

            aggregates
                .SentEventsTo<SampleEventRaised>(sampleEventHandler.HandleMessage)
                .AndTo<IAmAnEventMessage>(_ => { Console.WriteLine("--Message--\n"); });

**Comment by CarstenKoenig** [comment]
PS: `ExecutionResult` and `ExecutionFlags` are really badly named (**weasel** words) - can someone think of a better name?

Overall at first I thought it might be your usual error/either-monad but the way you use it here tell another story ...

**Comment by CarstenKoenig** [comment]
The last one might be controversial - I had a look at your `EventBag` and as the part you called `Event` really only carries some data/value-load (the rest that makes an event in my opinion: the id, versioning, ... - is all in the `EventBag` itself) so I renamed the stuff a bit.

**Pull request closed without merging**
